### ISSUE TITLE
false error "Selected file has no valid Lat Lon coordinates"

### ISSUE THREAD

**Issue by wilsberg** [FrankBijnen/ExifToolGui#251] opened 2024-01-11 18:55 UTC
On "Modify/Update City.." I get the false error message
"Selected file has no valid Lat Lon coordinates"
this can't be, because the cooredinates are correct.
If you want to try:
```
GPS Version ID                  : 2 3 0 0
GPS Latitude Ref                : N
GPS Latitude                    : 49.8910330217361
GPS Longitude Ref               : E
GPS Longitude                   : 2.30790023689444
GPS Altitude Ref                : 0
GPS Altitude                    : 28.468

```

**Comment by FrankBijnen** [comment] 2024-01-11 21:45
I believe you if you say that the file has coordinates. But maybe not in the Group ExifToolGui expects it.
 
The GPS tags can be in different groups. If you execute this command
-gpslatitude -a -g
It should also show the groupname. 

---- EXIF ----
GPS Latitude                    : 50.193791°
---- Composite ----
GPS Latitude                    : 50.193791° N
{ready26}

But the problem is likely that the file, or multiple files, have not been correctly selected.
How it works: 
- Select a number of files you wish to tag.
- The dialog takes the coordinates of the FIRST selected file, and uses that for all files.
- If the first selected file has no coordinates, you get the error.
 
I would like a screenshot from you like this.
![select](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/dee8fbbe-2627-4e4d-8f16-01bad6463ac4)

Frank

**Comment by wilsberg** [comment] 2024-01-11 23:00
I think with the different "GPS tags can be in different groups." you're right.
Here is the output:
PS C:\Daten\Bilder\2023_12_28> C:\Daten\Software\Exiftool\exiftool.exe -gpslatitude -a -g DP5A0019.CR3
---- EXIF ----
GPS Latitude                    : 49 deg 53' 27.72"
---- XMP ----
GPS Latitude                    : 49 deg 53' 27.72" N
---- Composite ----
GPS Latitude                    : 49 deg 53' 27.72" N

Thats seems correct.
But in your List it's not there the GPS is NO:
![list](https://github.com/FrankBijnen/ExifToolGui/assets/120686570/6441610b-5eb5-4f71-b253-622f67272bd5)

**Comment by FrankBijnen** [comment] 2024-01-11 23:22
Aha, I think I know what's going on.
The 'GPS' data in the filelist is not read by Exiftool, but directly by ExiftoolGUI. That was already the case in the old version 516.
Could you post a sample of a CR3 file, so I can check?
I might be possible to add support for CR3 files, I recently did it for FujiFilm Raw.

Frank

**Comment by wilsberg** [comment] 2024-01-12 06:44
I wrote you a mail with the file.

**Comment by FrankBijnen** [comment] 2024-01-12 07:47
Thank you,
Sadly I did not receive an email with an attachment. Maybe it's better to add it to the issue. To avoid problems with Spam/Virusscanners etc.
Frank

Use: 'Paste, drop or click to add files'

**Comment by wilsberg** [comment] 2024-01-12 08:13
Hi Frank,
ok, then on this way:
it looks like you said: I "geotagt" the CR3 file with Exiftool 5.16.0.0:

For your further examination here is the file: "Export/Import, Import GPS data from.., Log file" and then the gpx file from my garmin of the day.

https://c.gmx.net/@326982616148350005/C2kj5n7tT-O1mqRkPuJchQ

**Comment by FrankBijnen** [comment] 2024-01-12 09:48
Thanks I have downloaded it and am able to reproduce it.

Will look into it and keep you posted.

**Comment by wilsberg** [comment] 2024-01-12 10:09
thanks

**Comment by FrankBijnen** [comment] 2024-01-13 09:16
I have made progress, The info now shows in the FileList, and the dialog no longer gives the error.

If you would like to test it I could send you the updated exe. I prefer WeTransfer, but then I would need an Email address.

Frank

![cr3_1](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/fe459ca8-a3c8-41e2-b665-455c01f97ec0)
![cr3_2](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/4c8e0a1d-c131-41e2-be25-b7bb3f62ec2e)
![cr3_3](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/166d61f0-9002-4262-ac5d-3249811ff102)

**Comment by wilsberg** [comment] 2024-01-13 09:42
congratulations, how can I send you the Mail-adress?

**Comment by FrankBijnen** [comment] 2024-01-13 11:06
I understand you dont want to disclose your Mail address publicly. Same for me. I can think of 2 options:

1) If you are a member of https://exiftool.org/forum (or dont mind registering) send a PM to user FrankB.
2) Send a link from gmx.net (like you did with the sample CR3) with a text file containing your Mail address. When I have it, I will notify you, and you can delete it.

Would that work?

**Comment by wilsberg** [comment] 2024-01-13 12:26
I've send PM to user FrankB;-)

**Comment by wilsberg** [comment] 2024-01-13 13:59
The version is fine. - thanks a lot.

**Comment by FrankBijnen** [comment] 2024-01-13 14:05
Ah... That's good news. Thanks for testings.

Please keep using this version. Should you find anything else related to this issue, post it here please.

Will be in the next release. End of Januari.
Frank

**Closed** 2024-01-13 23:29 UTC

**Comment by FrankBijnen** [comment] 2024-01-28 09:13
Just to let you know. The changes mentioned in this issue are now available in a new release:

https://github.com/FrankBijnen/ExifToolGui/releases/tag/V6.2.9

Thanks for your input,
Frank
