### ISSUE TITLE
LocationInfo Filelist

### ISSUE THREAD

**Issue by Philshappy** [FrankBijnen/ExifToolGui#356] opened 2024-03-16 19:51 UTC
Is there a reason why the LocationInfo columns is not always showing the updated Country and State. The two screenshots show the metadata is present in both photos but not displayed in the LocationInfo. If I create a custom user than the info is show in both. Attached are screen shots showing the LocationInfo columns and the metadata.

Version 6_30 is awesome. Thanks!

![With](https://github.com/FrankBijnen/ExifToolGui/assets/149206994/b2a16917-c4bb-4ccc-a12c-67d931e5984e)
![Without](https://github.com/FrankBijnen/ExifToolGui/assets/149206994/a360af2a-0076-469a-aeed-7f9f3543814b)

**Comment by FrankBijnen** [comment] 2024-03-16 20:42
What are the filetypes?

Background: If you select 'LocationInfo' then GUI tries to read the data directly from the file, and it does not use  ExifTool to speed things up. In the Metadata panel and the 'custom user' you see ExifTool generated data. But GUI knows only how to read a few filetypes, compared to ExifTool.

Poosbile workaround: Preferences/Other Check 'Filelist: Enable Camera Settings, Location info and About Photo for all file types.

**Comment by Philshappy** [comment] 2024-03-16 20:53
All file are jpg. The files but 2 different cameras, Canon PowerShot G9 X Mark II shows the location data, Pixel 7 Pro does not. The workaround did not fix it. Its not a problem for me I can use the custom user, just thought you might want to know and possible look into it for a future release. Also, I really like the custom user list so maybe add the ability to have 2-3 custom lists like the workspace which allows more than 1.
________________________________

**Comment by FrankBijnen** [comment] 2024-03-16 20:59
Ah. Seems related to the file type. Would you mind sharing one from the Pixel 7 Pro, that does not work?

Something else I would like to know. How did you update the 'location info'? Via this menu? And what was your input?

![a](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/4464d905-027e-4177-9adf-81c36721e603)

**Comment by FrankBijnen** [comment] 2024-03-16 21:02
Ah.It seems file type related. Would you mind sharing a Pixel Pro 7 sample?

And I would like to know how did you update the City, Country etc? 

This form? and what were your parms?
![a](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/e4738a86-b1a2-495f-8c66-bcf241180ada)

**Comment by Philshappy** [comment] 2024-03-16 21:17
Default was the settings when I first noted the issue.

Changed is the settings changed to match your email.

The other screen shot is the geotag results.

To determine the location I used your tool, since the photo already had the geolocation, i clicked show on map, then geotag.

I also included the photo.



________________________________

**Comment by FrankBijnen** [comment] 2024-03-16 21:57
Sorry, but I see no screenshots, nor image. If you reply by email, Github removes all attachments,

Still no idea what's going on. Some more questions.
- So you did not use 'Modify/Update City etc..', but you used the 'Geotag files' button?
- And what was the provider you did choose? 'ExifTool', Overpass or Geocode?
- Can you do it again and first open the log Window. You can send the commands, output and errors as text.

Thanks in advance,
Frank

**Comment by Philshappy** [comment] 2024-03-16 22:15
This was the settings when i noted the issue.
![Default Setting](https://github.com/FrankBijnen/ExifToolGui/assets/149206994/2c83b676-4c3d-4375-a258-09bce6a95379)

This is the settings after you sent me an email and I changed it to match yours.
![Changed Setting](https://github.com/FrankBijnen/ExifToolGui/assets/149206994/b1f1c417-a9db-4c0a-964d-bbceb567ee94)

They produced the same results.

This is the geotag results.
![Geotag Results](https://github.com/FrankBijnen/ExifToolGui/assets/149206994/861f6a11-3534-4e92-80e0-55df7a14830b)

To determine the location I used your tool, since the photo already had the geolocation, i clicked show on map, then geotag.

This is the photo.
![PXL_IMG1](https://github.com/FrankBijnen/ExifToolGui/assets/149206994/fdc6c110-5cb9-432b-adc9-b99cbd8a329d)

**Comment by Philshappy** [comment] 2024-03-16 22:18
So you did not use 'Modify/Update City etc..', but you used the 'Geotag files' button?
Correct

And what was the provider you did choose? 'ExifTool', Overpass or Geocode?
Both Exif and overpass, same results

Can you do it again and first open the log Window. You can send the commands, output and errors as text.
Will do.

Oh and very important. Did it work in the previous version?
No it did not

**Comment by Philshappy** [comment] 2024-03-16 22:20
![Screenshot 2024-03-16 151919](https://github.com/FrankBijnen/ExifToolGui/assets/149206994/f379a017-bebd-4698-90d9-d854c993cc8f)

-echo4
{ready17}
-CHARSET
FILENAME=UTF8
-CHARSET
UTF8
-v0
-overwrite_original
-sep
*
-m
-c
%.6f°
-API
WindowsWideFile=1
-a
-Gps*=
--GPSversion*
-GPS:GpsLatitudeRef=N
-GPS:GpsLatitude=40.607575
-GPS:GpsLongitudeRef=W
-GPS:GpsLongitude=111.483303
-QuickTime:GPSCoordinates='40.60757, -111.4833, 0'
-xmp:CountryCode=US
-xmp:Country=United States
-xmp:State=Utah
-xmp:City=Park City
-xmp:LocationShownCountryCode=US
-xmp:LocationShownCountryName=United States
-xmp:LocationShownProvinceState=Utah
-xmp:LocationShownCity=Park City
-xmp:LocationShownSublocation=
PXL_IMG1.jpg
-execute17

**Comment by Philshappy** [comment] 2024-03-16 22:24
It appears that the tool is saving the correct data, as i can see it in the metadata and my custom user filelist.

**Comment by Philshappy** [comment] 2024-03-16 22:25
It appears that the tool is saving the correct data, as i can see it in the metadata and my custom user filelist.

**Comment by FrankBijnen** [comment] 2024-03-16 23:06
Thanks a lot.
I'm able to reproduce it now, with the picture you sent. Will dive into it.

**Comment by FrankBijnen** [comment] 2024-03-16 23:32
@Philshappy 
I have uploaded a patched version to my onedrive.
https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

Can you confirm that that works? (You will need to check Preferences/Other Check 'Filelist: Enable Camera Settings, Location info and About Photo for all file types.)

Frank

**Comment by Philshappy** [comment] 2024-03-17 00:00
Yes it worked after enabling Preferences/Other Check 'Filelist: Enable Camera Settings, Location info and About Photo for all file types. 
![Screenshot 2024-03-16 165739](https://github.com/FrankBijnen/ExifToolGui/assets/149206994/d7b346c2-29a6-47f4-a464-e067643cc44f)

**Comment by Philshappy** [comment] 2024-03-17 00:01
Just curious why the canon photos worked fine but the pixel photos did not.

**Comment by FrankBijnen** [comment] 2024-03-17 07:42
Very good news that it works now! Thanks for confirming.

Planning:
- At the moment I dont want to release a new version. You can keep using the patched versions.
- I will commit the changes to Github, close the issue. Will be available in a next release. 
- Your remark about save the custom filelist settings I will not forget. I will add it to an existring issue. https://github.com/FrankBijnen/ExifToolGui/issues/351 Also next release
- Non technical reason: Now that spring has arrived I want to slow down with GUI development anyway. 

Explanations:
- The Pixel 7 pro stores the 'XMP data' different. (It looks encrypted to me) Good news is that ExifTool knows how to handle it.
- As explained earlier GUI tries to read the data directly from the file, to speed things up. If it finds that it can not handle the file the method that does that returns 'Unsupported' and GUI calls upon ExifTool to get the data.
- For the data in 'Location Info', you need the info from 2 groups: ExifIFD and XMP. ExifIFD can be read by GUI.

- There were 2 things that went wrong in GUI.
- 1) In the case that XMP data could be read, but was 'encrypted', the method still returned 'Supported'.
- 2) GUI only checked for ExifIFD=supported, and not for XMP=supported, and failed to call upon ExifTool.

Note: the column 'GPS' was correctly displayed, that info comes from ExifIFD 

Frank

**Closed** 2024-03-17 08:04 UTC

**Comment by FrankBijnen** [comment] 2024-03-17 11:47
@Philshappy 

Just one more remark I kept forgetting to make. In one of your screenshots I saw that you use ExifTool Version 12.77. To use the 'Exiftool geocode provider' you need ExifTool Version 12.79.

**Comment by Philshappy** [comment] 2024-03-17 14:37
Thanks for explaining it. GUI was using Exiftool 12.79 and not 12.77  I am guessing that 12.77 was used earlier and somehow got recorded in the metadata, maybe when I first updated the location data.
________________________________

**Comment by FrankBijnen** [comment] 2024-03-17 16:00
OK. Must be my age.

But the story is not over yet! I couldn't let go and wanted to know why ExifTool was able to read the XMP. As it turns out in your sample there a 3 XMP sections.
1st = a 'normal' section.
2nd and 3rd are 'extended'. What I described earlier as encrypted.

What GUI did was read the last section, and it couldn't cope with that. I have changed the code to check for the 'type of the XMP' and it now reads the 1st and skips the other 2. 
For an end-user may be not that interesting, but the advantage is that it processes the file(s) much faster, and you dont need to enable the checkbox in Preferences

Will be in a next release, and thanks for your help!
Frank

**Comment by Philshappy** [comment] 2024-03-17 17:59
I have also noted that some of the XMP metadata is unique to the maker and therefore I have used the '*' in front of the 
 command to find it or modify it. For example the metadata CanonTimeZone:TimeZone is unique to Canon or NikonTimeZone:TimeZone is unique to Nikon so now when saving to workspace I save -*:TimeZone and it finds either of them.
