### ISSUE TITLE
Bug / Improvement: Custom Config Option Not Honored as First Argument in ExifToolGUI

### ISSUE THREAD

**Issue by djdarcy** [FrankBijnen/ExifToolGui#296] opened 2024-02-13 05:28 UTC
**Description**:
When using ExifToolGUI to edit image metadata with custom XMP fields, the GUI does not correctly handle the -config argument for ExifTool. Although the custom configuration file is specified, it is appended at the end of the command line arguments rather than being placed as the first argument, resulting in the -config option being ignored by ExifTool. This prevents the custom XMP fields from being recognized and editable within the GUI.

**Repro Steps:**

1. Open ExifToolGUI and navigate to Options → Custom Options.
2. Enter the custom option `-config customtags.cfg` to specify a custom configuration for ExifTool. (see *Personal Use Case* below for example cfg)
3. Attempt to edit an image file with custom XMP fields defined in customtags.cfg.
4. Observe that the changes are not saved and an error is outputted indicating that the -config option is ignored because it is not first.

**Expected**:
The expected behavior is for ExifToolGUI to prepend the specified -config argument at the beginning of the command line for ExifTool, ensuring that the custom configuration file is correctly read and the custom XMP fields are accessible and editable within the GUI.

**Actual**:
ExifToolGUI appends the -config argument at the end of the command line, causing ExifTool to ignore the custom configuration file and resulting in custom XMP fields not being recognized or editable within the GUI.

**Suggested Fix**:
Modify ExifToolGUI to allow the -config option to be placed as the first argument in the command line when building ExifTool commands, in accordance with ExifTool's requirements for custom configuration files.

**Personal Use Case**:
[custom-url-xmp.zip](https://github.com/FrankBijnen/ExifToolGui/files/14256592/custom-url-xmp.zip) (or see [customtags.cfg in gist](https://gist.github.com/djdarcy/5dbb129071f01041ace5e8abf1980baf#file-customtags-cfg))
`exiftool -config customtags.cfg -URLInstagram="http://instagram.com/yourusername" "pic.png"`
*start ExifToolGUI and modify social media links using something like*:
`exiftool -config customtags.cfg  -echo4 {ready86} -CHARSET FILENAME=UTF8 -CHARSET UTF8 -v0 -overwrite_original -sep * -c %.6f° -API WindowsWideFile=1 -xmp-socialmedia:urlinstagram=http://instagram.com/yourusername pic.png -execute86`

**Additional Information**:
Running: 6.2.9 ExifToolGUI and 12.76 exiftool on Win 10 x64

**Impact**:
This issue prevents users from leveraging the full capabilities of custom XMP fields within ExifToolGUI, limiting the metadata editing workflow and requiring manual command line operations for tasks that should be achievable via the GUI.

**Comment by djdarcy** [comment] 2024-02-13 06:40
I've been using a simple python script ([gist available here](https://gist.github.com/djdarcy/5dbb129071f01041ace5e8abf1980baf#file-exiftool-py)) in the interim to accomplish what I need. Hopefully this gives a better sense of what I'm shooting for in the *Personal Use Case* above, in case anything is unclear.

**Comment by FrankBijnen** [comment] 2024-02-13 09:02
@djdarcy 

Thanks for this issue. I really like this kind of input.

I had a quick look, and my first thought is: Internally ExifToolGui passes ALL arguments via an ARGS file and the only option on the command line is 'exiftool -@ "' + TempFile + '"';  (Where TempFile is the name of the ARGS file)
The custom option(s) is also written to the ARGS file and not used on the command line. Maybe that needs changing.

If I have something to test can I ask you to do that?

Frank

**Comment by FrankBijnen** [comment] 2024-02-13 10:27
Having looked deeper into this, my suspicion is confirmed. The -config option needs to be on the commandline, it can not be used in an args file. And I really need to keep using args files, because they solve all kind of UTF8 problems.  
The commandline that works is something like this 'exiftool -config "config_file" - @ args_file'

I have made some modifications and compiled it as Prerel 6.3.0. With this version you can specify, in the INI file directly, not in the GUI, a line 'ETCustomConfig='
With this option I'm able to update your supplied XMP tags.

Could you please download that version and test it yourself?
https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

If the test is successful we can later discuss how to add in ExifToolGui. (I dont want to add it to 'Custom options', because it works different)

Relative to ExifTool.exe:
ETCustomConfig=customtags.cfg

Absolute path:
ETCustomConfig=C:\ExifToolGUI\custom_config\customtags.cfg

Part of the INI file
```
[GUIsettings]
Language=
AutoRotatePreview=1
FileFilters=*.JPG|*.CR2|*.JPG;*.CR2|*.JPG;*.DNG|*.JPG;*.PEF
DefStartupUse=0
DefStartupDir=c:\
ETOverrideDir=
ETCustomConfig=<Config file to use>
ETTimeOut=5000
DefExportUse=0
DefExportDir=

```

**Comment by djdarcy** [comment] 2024-02-15 20:56
@FrankBijnen Thanks for the quick patch and the insightful explanation! The ini solution `ETCustomConfig=[fully-qualified-path]\[config-file].cfg`  works exactly I'd hope. It make sense to me that the cfg file should be treated differently and not just relegated to the "custom option" field. Ideally it would be nice if a DataGrid / Listview control existed to simplify editing parts of the ini. But if you are brainstorming how to better integrate custom XMP metadata, then perhaps the workspace manager could incorporate an OpenFileDialog Windows form to write a line into the workspace ini more strongly associating the workspace ini directly with the grammar itself? I'm happy to brainstorm a bit more with you if you'd like. Thanks for the fix, this is very helpful! 
Regards, 
Dustin

**Comment by djdarcy** [comment] 2024-02-15 20:57
@FrankBijnen Thanks for the quick patch and the insightful explanation! The ini solution ETCustomConfig=[fully-qualified-path]\[config-file].cfg works exactly I'd hope. It make sense to me that the cfg file should be treated differently and not just relegated to the "custom option" field. Ideally it would be nice if a DataGrid / Listview control existed to simplify editing parts of the ini. But if you are brainstorming how to better integrate custom XMP metadata, then perhaps the workspace manager could incorporate an OpenFileDialog Windows form to write a line into the workspace ini more strongly associating the workspace ini directly with the grammar itself? I'm happy to brainstorm a bit more with you if you'd like. Thanks for the fix, this is very helpful!
Regards,
Dustin

**Comment by djdarcy** [comment] 2024-02-15 21:10
Reopening just so you have the chance to look at my comment and to make it easier for tracking, but if you are happy with the solution you implemented - it gets the job done, so no complaints on my end. :)

**Comment by FrankBijnen** [comment] 2024-02-15 21:17
@djdarcy Thanks for your feedback.

A few (unrelated) remarks
- This issue will be included in the next version. Will be named 6.3, and hopefully incude some language modules. That's why I dont want to much GUI changes with texts that need translating.
- Your suggestion to add the parameter 'CustomConfig' to the Workspace I have to think about. I have little experience with custom configs, but I have the feeling that one can do more than just custom tags. So would an average user look for the option there?
- I had 2 options in mind. 1) Add a field to the preferences, tab page 'Other', just under 'Exiftool location'. with a button to have an open dialog. 2) Add a menuitem under 'Options', just under 'Custom Options'.
- Reminder for myself: If the user adds/changes/deletes a custom config, the running ExifTool has to be restarted so the changes take effect.

But please tell me what you think.

Frank

**Comment by FrankBijnen** [comment] 2024-03-05 10:45
@djdarcy 

I have add the option to specify a custom config to the preferences form, and closed the issue.

Frank

**Closed** 2024-03-05 10:46 UTC
