### ISSUE TITLE
[Feature request] deletion of files

### ISSUE THREAD

**Issue by AngusPhoe** [FrankBijnen/ExifToolGui#273] opened 2024-01-21 16:55 UTC
Hello Frank,

I think one could delete files directly within the old Bolgdan version of ExifToolGui. Can you bring back this feature? 

If yes, I can imagine that some people would like to decide, wheather they want a confirmation pop up or not. For me personally it does not matter.

Kind regards,
Angus

**Comment by FrankBijnen** [comment] 2024-01-21 17:42
Hello Angus,

It is still possible to delete files & folders. It's in the contextmenu of the filelist and folder treeview. (Rightclick / delete). The confirmation is there. Maybe configurable in windows settings.
There's no keyboard shortcut.

Frank

**Comment by AngusPhoe** [comment] 2024-01-21 18:17
Thanks for the quick response. 

I did not think of the context menu. That's indeed a way to delete files.

I should have decribed my feature request more precisely: I wanted to ask if deletion of files can be done by using the key shortcut DEL? 

I hope I am not the (shortcut) pain in the neck. 😟

**Comment by FrankBijnen** [comment] 2024-01-21 18:32
"I should have decribed my feature request more precisely: I wanted to ask if deletion of files can be done by using the key shortcut DEL?"

That's why I mentioned it.

"I hope I am not the (shortcut) pain in the neck. 😟"
I'm not native English, but I believe its 'a pain in some other bodypart"

I will think about it. The problem is, that by enabling it now it could come to a surprise to people who never knew the old version. I'm thinking of CTRL+DEL. Will keep you posted.

**Comment by FrankBijnen** [comment] 2024-01-21 22:11
@AngusPhoe 

I did some investigating. I <b>can</b> get a shortcut working. (DEL key, or CTRL+DEL) But I'm still hesitating if I should.

But... Can you live with this suggestion?

-SHIFT F10. This pops up the contextmenu.
-Press 'd'. That is the shortcut for 'Delete' in the Contextmenu.

Works with multi-select.

Frank

**Comment by AngusPhoe** [comment] 2024-01-22 19:27
Hi Frank,

in fact I thought long about my request. If I consider ExifToolGui simply as a GUI for exiftool.exe, deleting files wouldn't be in the scope of the program. And indeed, I usually never sort out files (from the masses of photo and video files I take) with ExifToolGui. It was a seldon coincidence that I wanted to delete a file from within ExifToolGui.

So, to sum it up: I am happy with every solution, also with the existing one with Shift+F10 and then D.

Kind regards,
Angus

**Comment by FrankBijnen** [comment] 2024-01-22 19:35
OK. Thanks for that.

I will close the issue, but will keep the code to delete the files should it ever be needed.

Just out of curiousity. What's your native Language? Would you be interested in a multilingual version of ExifToolGui? I'm thinking of adding that.

Frank

**Closed by FrankBijnen** 2024-01-22 19:35 UTC

**Comment by AngusPhoe** [comment] 2024-01-22 20:03
Hi Frank,

My native language is German. I personally always use the English version of programs even if a German translation exists.

But I can offer my support for translating the program if needed.

Angus

**Comment by FrankBijnen** [comment] 2024-01-28 09:08
Hi Angus,

Just to let you know. New version released, including some, or all, of your suggestions.
https://github.com/FrankBijnen/ExifToolGui/releases/tag/V6.2.9

I started work on translating: 
https://github.com/FrankBijnen/ExifToolGui/tree/main/Translation

Thanks 
Frank

**Comment by AngusPhoe** [comment] 2024-01-28 19:39
Thanks for all your work! Appreciate this!

Regarding the translation (into German). I will look into this during one of the next days and will get back to you (haven't done this before).

**Comment by AngusPhoe** [comment] 2024-02-06 19:51
Hello Frank,

I am very sorry: I am very busy right now and haven't managed to look at the translation, yet. I hope I can york on this next week.

Ragards,
Angus
